// libs/angular-ui/auth/src/lib/sign-up/sign-up.component.ts
import { Component } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { SignUpRequest } from '@bootstrapbugz/shared';
import { Store } from '@ngrx/store';
import { signUp } from '../+state/auth.actions';
import { AuthState } from '../+state/auth.reducer';

@Component({
  selector: 'bootstrapbugz-sign-up',
  templateUrl: './sign-up.component.html',
  styleUrls: ['./sign-up.component.scss'],
})
export class SignUpComponent {
  signUpForm = new FormGroup({
    firstName: new FormControl('', Validators.required),
    lastName: new FormControl('', Validators.required),
    username: new FormControl('', Validators.required),
    email: new FormControl('', Validators.required),
    password: new FormControl('', Validators.required),
    confirmPassword: new FormControl('', Validators.required),
  });

  constructor(private store: Store<AuthState>) {}

  onSignUp() {
    const request = this.signUpForm.value as SignUpRequest;
    this.store.dispatch(signUp({ request }));
  }
}

<mat-card>
  <mat-card-content>
    <form [formGroup]="signUpForm" (ngSubmit)="onSignUp()">
      <h2>Sign Up</h2>
      <mat-form-field appearance="outline">
        <mat-label>First Name</mat-label>
        <input matInput type="text" [formControl]="signUpForm.get('firstName')" />
      </mat-form-field>
      <mat-form-field appearance="outline">
        <mat-label>Last Name</mat-label>
        <input matInput type="text" [formControl]="signUpForm.get('lastName')" />
      </mat-form-field>
      <mat-form-field appearance="outline">
        <mat-label>Username</mat-label>
        <input matInput type="text" [formControl]="signUpForm.get('username')" />
      </mat-form-field>
      <mat-form-field appearance="outline">
        <mat-label>Email</mat-label>
        <input matInput type="email" [formControl]="signUpForm.get('email')" />
      </mat-form-field>
      <mat-form-field appearance="outline">
        <mat-label>Password</mat-label>
        <input matInput type="password" [formControl]="signUpForm.get('password')" />
      </mat-form-field>
      <mat-form-field appearance="outline">
        <mat-label>Confirm Password</mat-label>
        <input matInput type="password" [formControl]="signUpForm.get('confirmPassword')" />
      </mat-form-field>
      <button mat-raised-button color="primary" type="submit">Sign Up</button>
    </form>
  </mat-card-content>
</mat-card>

// svelte-kit/src/routes/auth/sign-up/+page.svelte
<script lang="ts">
  import { Button, Card, Input, Label } from 'flowbite-svelte';
</script>

<div class="flex justify-center pt-10">
  <Card size="sm" class="w-full">
    <form class="flex flex-col space-y-6" action="/">
      <h3 class="grid justify-items-center p-0 text-xl font-medium text-gray-900 dark:text-white">
        Sign up to BootstrapBugZ
      </h3>
      <Label class="space-y-2">
        <span>First name</span>
        <Input name="firstName" required />
      </Label>
      <Label class="space-y-2">
        <span>Last name</span>
        <Input name="lastName" required />
      </Label>
      <Label class="space-y-2">
        <span>Username</span>
        <Input name="username" required />
      </Label>
      <Label class="space-y-2">
        <span>Email</span>
        <Input name="email" required />
      </Label>
      <Label class="space-y-2">
        <div class="flex justify-between">
          <span>Password</span>
        </div>
        <Input type="password" name="password" required />
      </Label>
      <Label class="space-y-2">
        <div class="flex justify-between">
          <span>Confirm Password</span>
        </div>
        <Input type="password" name="confirmPassword" required />
      </Label>
      <Button type="submit" class="w-full">Sign up</Button>
    </form>
  </Card>
</div>

<style>
</style>
